# parameters for modeling pipe
evaluation:
  random_seed: 42
  split_count: 8
  split_fraction: 0.5
  fraction: 
model:
  random_seed: 42
  epochs: 3
  k: 5
  n_components: 50
  loss: warp
# Parameters for indexing
index_params:
  n_trees: 10
  metric: dot